services:
  transactions:
    build:
      context: .
      dockerfile: src/CashFlow.Transactions/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AppSettings__Seq__Url=http://seq:80      
    ports:
      - "5001:8080"
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - cashflow-network      

  consolidation:
    build:
      context: .
      dockerfile: src/CashFlow.Consolidation/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AppSettings__Seq__Url=http://seq:80
    ports:
      - "5002:8080"
    depends_on:
      - mysql
      - rabbitmq
    networks:
      - cashflow-network      

  apigateway:
    build:
      context: .
      dockerfile: src/CashFlow.ApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - AppSettings__Seq__Url=http://seq:80
    ports:
      - "5000:8080"
    depends_on:
      - transactions
      - consolidation
    networks:
      - cashflow-network      

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=123P@$$Word!
      - MYSQL_DATABASE=cashflowdb
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cashflow-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cashflow-network
      
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: "Y"
    networks:
      - cashflow-network
     
volumes:
  mysql_data:
  
networks:
  cashflow-network:
    driver: bridge
    name: cashflow-network
