services:
  transactions:
    build:
      context: .
      dockerfile: src/CashFlow.Transactions/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - cashflow-network      

  consolidating:
    build:
      context: .
      dockerfile: src/CashFlow.Consolidating/Dockerfile
    ports:
      - "5002:80"
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - cashflow-network      

  apigateway:
    build:
      context: .
      dockerfile: src/CashFlow.ApiGateway/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - transactions
      - consolidating
    networks:
      - cashflow-network      

  postgres:
    image: postgres:15-alpine
    environment: 
      - POSTGRES_USER=postgres    
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cashflowdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cashflow-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cashflow-network

volumes:
  postgres_data:
  
networks:
  cashflow-network:
    driver: bridge
    name: cashflow-network
